#!/bin/bash

echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (PCA, no pruning, cuts for full sim, reweighted sig samples, test on different weights and correct var. order, qq background included)' >> outSig.txt

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/BP21_DataPreselected.root inputs/R12_reweighted/BP23_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "BP21",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   6459.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "_allBackgrounds_withCuts",
                 "on")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/BP21_DataPreselected.root inputs/R12_reweighted/BP23_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "BP23",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   8490.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "_allBackgrounds_withCuts",
                 "on")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/HP17_DataPreselected.root inputs/R12_reweighted/HP20_DataPreselected.root inputs/R12_reweighted/HP3_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2011.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "_allBackgrounds_withCuts",
                 "off")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/HP17_DataPreselected.root inputs/R12_reweighted/HP20_DataPreselected.root inputs/R12_reweighted/HP3_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2642.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "_allBackgrounds_withCuts",
                 "off")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/HP17_DataPreselected.root inputs/R12_reweighted/HP20_DataPreselected.root inputs/R12_reweighted/HP3_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   3153.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "_allBackgrounds_withCuts",
                 "off")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

: << 'END'

root -l -q my_mva_selection.C++'("inputs/R12_reweighted/HP17_DataPreselected.root inputs/R12_reweighted/HP20_DataPreselected.root inputs/R12_reweighted/HP3_DataPreselected.root",
         			   "inputs/R12_reweighted/qqll_DataPreselected.root inputs/R12_reweighted/qqlv_DataPreselected.root inputs/R12_reweighted/ll_DataPreselected.root inputs/R12_reweighted/qqqq_DataPreselected.root inputs/R12_reweighted/qqvv_DataPreselected.root inputs/R12_reweighted/qqlvlv_DataPreselected.root inputs/R12_reweighted/qqlvvv_DataPreselected.root inputs/R12_reweighted/qqqqlv_DataPreselected.root inputs/R12_reweighted/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "leptonTheta leptonPt MET missingMass jet2Theta jet1Pt",
         			   "Ievt crossSection sampleName w",
         			   2642.0,
         			   1352621.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
"",
"off")' >> out.log
END
