#!/bin/bash

echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (PCA, cuts for fast sim, all backgrounds, signal sample splitted, no Mlv)' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/BP21_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "BP21",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   6460.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/BP23_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "BP23",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   8494.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/HP17_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   2015.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/HP20_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   2644.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/HP3_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   3154.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

: << 'END'


root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/HP20_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   2644.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' #| awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt


root -l -q my_mva_selection_ss.C++'("inputs/R12_allBackgrounds_fastSimCuts/HP20_DataPreselected.root",
         			   "inputs/R12_allBackgrounds_fastSimCuts/qqll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/ll_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqq_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqlvvv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qqqqlv_DataPreselected.root inputs/R12_allBackgrounds_fastSimCuts/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "Ievt crossSection sampleName w",
         			   2642.0,
         			   1352347.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")'
END
