#!/bin/bash

                                  #### WITH OVERLAY ####

          echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (with overlay, cuts for fast sim., PCA, no pruning, missing P4 like in full sim, split signal for training, no Mlv)' >> singleSampleResults.txt

root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP3_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   3429.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP17_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   2024.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
         			   "Ievt crossSection sampleName w",
         			   2952.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_BP21_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "BP21",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
			    "Ievt crossSection sampleName w",
			    7733.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_BP23_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "BP23",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E",
			    "Ievt crossSection sampleName w",
			    10071.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt


: << 'END'

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_BP18_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "BP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   9234.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			   "UseNvars=6",
                 "withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "BP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP2_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP2",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   1024.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP2",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP3_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   3429.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP5_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP5",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2296.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP5",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP6_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP6",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   1377.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP6",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP7_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP7",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   1286.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP7",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP8_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP8",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   825.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP8",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP9_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP9",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   1132.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP9",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP10_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP10",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   414.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP10",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP11_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP11",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   6524.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP11",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP12_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP12",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   3884.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP12",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP13_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP13",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   5788.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP13",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP14_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP14",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2633.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP14",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP15_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP15",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   5815.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP15",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP16_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP16",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   5080.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP16",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP17_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2024.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP18_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   4752.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP19_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP19",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   4126.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP19",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
         			   "Ievt crossSection sampleName w",
         			   2952.0,
         			   865865.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "P",
         			    "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_BP21_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "BP21",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
			    "Ievt crossSection sampleName w",
			    7733.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_BP23_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "BP23",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
			    "Ievt crossSection sampleName w",
			    10071.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP1_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "HP1",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
			    "Ievt crossSection sampleName w",
			    7811.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP1",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

          root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
			    "HP4",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E M_inv_Wlep",
			    "Ievt crossSection sampleName w",
			    3245.0,
			    865865.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "P",
			     "UseNvars=6",
"withOverlay_alternativeMissingP4")' | awk '/^---        BDT:/ {print "HP4",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

END

: << 'END'

root -l -q my_mva_selection_test.C++'("root_withOverlay_alternativeMissingP4/idm_hphm_slep_HP20_3000DataPreselected.root",
       "root_withOverlay_alternativeMissingP4/idm_bg_ll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqll_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqlvvv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqq_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqqqlv_3000DataPreselected.root root_withOverlay_alternativeMissingP4/idm_bg_qqvv_3000DataPreselected.root",
       "HP20",
       "",
       "missingMass M_inv_Wlep jetsEnergy jet1E leptonPt jet1Pt MET jetsM_inv jet2E jet2Pt EFsum jetDeltaPhi jetDeltaTheta jet2Theta jetsTheta jet1Theta leptonTheta",
       "Ievt crossSection sampleName w",
       2952.0,
       865865.0,
       "",
       "",
       "w",
       "my_mva_selection_test",
       "1000",
       "P",
        "",
"withOverlay_alternativeMissingP4")' # | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

END
