#!/bin/bash

: << 'END'

          echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (no smear, correlated MET, regular EFlow, fixed NJets)' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "BP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   9514.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			   "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
                 "root_noSmear")' | awk '/^---        BDT:/ {print "BP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP2",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1125.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP2",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   3462.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP5",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2707.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP5",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP6",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1507.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP6",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP7",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1442.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP7",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP8",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   918.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP8",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP9",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1226.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP9",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP10",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   367.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP10",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP11",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6974.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP11",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP12",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   4074.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP12",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP13",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6418.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP13",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP14",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2737.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP14",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP15",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6181.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP15",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP16",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   5699.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP16",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2201.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   5273.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP19",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   4693.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP19",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP2_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP3_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP5_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP6_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP7_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP8_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP9_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP10_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP11_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP12_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP13_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP14_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP15_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP16_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP17_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP18_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP19_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   3235.0,
         			   743701.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP21_3000DataPreselected.root root_noSmear/idm_hphm_slep_BP23_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP1_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
			    "BP21",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    8036.0,
			    743701.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP21_3000DataPreselected.root root_noSmear/idm_hphm_slep_BP23_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP1_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
			    "BP23",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    10285.0,
			    743701.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP21_3000DataPreselected.root root_noSmear/idm_hphm_slep_BP23_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP1_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
			    "HP1",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    8019.0,
			    743701.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP1",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_noSmear/idm_hphm_slep_BP21_3000DataPreselected.root root_noSmear/idm_hphm_slep_BP23_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP1_3000DataPreselected.root root_noSmear/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_noSmear/idm_bg_ll_3000DataPreselected.root root_noSmear/idm_bg_qq_3000DataPreselected.root root_noSmear/idm_bg_qqll_3000DataPreselected.root root_noSmear/idm_bg_qqlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvlv_3000DataPreselected.root root_noSmear/idm_bg_qqlvvv_3000DataPreselected.root root_noSmear/idm_bg_qqqq_3000DataPreselected.root root_noSmear/idm_bg_qqqqlv_3000DataPreselected.root root_noSmear/idm_bg_qqvv_3000DataPreselected.root",
			    "HP4",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    3373.0,
			    743701.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"root_noSmear")' | awk '/^---        BDT:/ {print "HP4",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt


END

            #### WITH SMEAR ####




          echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (smear, new steering card)' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "BP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   9431.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			   "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
                 "withSmear1_newCard")' | awk '/^---        BDT:/ {print "BP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP2",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1148.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP2",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   3546.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP5",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2758.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP5",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP6",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1511.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP6",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP7",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1467.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP7",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP8",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   932.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP8",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP9",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1288.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP9",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP10",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   372.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP10",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP11",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6953.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP11",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP12",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   4076.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP12",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP13",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6400.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP13",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP14",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2754.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP14",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP15",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   6184.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP15",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP16",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   5709.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP16",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   2190.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP18",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   5273.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP18",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP19",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   4714.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP19",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP2_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP3_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP5_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP6_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP7_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP8_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP9_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP10_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP11_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP12_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP13_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP14_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP15_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP16_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP17_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP18_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP19_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP20_3000DataPreselected.root",
         			   "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   3265.0,
         			   1070647.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection_test",
         			   "1000",
         			   "I",
         			    "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP21_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_BP23_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP1_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
			    "BP21",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    7984.0,
			    1070647.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP21_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_BP23_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP1_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
			    "BP23",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    10304.0,
			    1070647.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP21_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_BP23_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP1_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
			    "HP1",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    8049.0,
			    1070647.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP1",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

          root -l -q my_mva_selection_test.C++'("root_withSmear1_newCard/idm_hphm_slep_BP21_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_BP23_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP1_3000DataPreselected.root root_withSmear1_newCard/idm_hphm_slep_HP4_3000DataPreselected.root",
			    "root_withSmear1_newCard/idm_bg_ll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqll_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqlvvv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqq_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqqqlv_3000DataPreselected.root root_withSmear1_newCard/idm_bg_qqvv_3000DataPreselected.root",
			    "HP4",
			    "",
				  "jetsM_inv jetsEnergy jetsTheta leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
			    "w",
			    3381.0,
			    1070647.0,
			    "",
			    "",
			    "w",
			    "my_mva_selection_test",
			    "1000",
			    "I",
			     "UseNvars=6:PruneMethod=CostComplexity:PruneStrength=-1",
"withSmear1_newCard")' | awk '/^---        BDT:/ {print "HP4",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt
