#!/bin/bash

echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (PCA, no pruning, fast sim cuts, qq bg. included, signal sample splitted, no Mlv )' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R09_fastSimCuts/BP21_DataPreselected.root",
         			   "inputs/R09_fastSimCuts/qqll_DataPreselected.root inputs/R09_fastSimCuts/qqlv_DataPreselected.root inputs/R09_fastSimCuts/ll_DataPreselected.root inputs/R09_fastSimCuts/qqqq_DataPreselected.root inputs/R09_fastSimCuts/qqvv_DataPreselected.root inputs/R09_fastSimCuts/qqlvlv_DataPreselected.root inputs/R09_fastSimCuts/qqlvvv_DataPreselected.root inputs/R09_fastSimCuts/qqqqlv_DataPreselected.root inputs/R09_fastSimCuts/qq_DataPreselected.root",
         			   "BP21",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   9108.0,
         			   1663980.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R09_fastSimCuts/BP23_DataPreselected.root",
         			   "inputs/R09_fastSimCuts/qqll_DataPreselected.root inputs/R09_fastSimCuts/qqlv_DataPreselected.root inputs/R09_fastSimCuts/ll_DataPreselected.root inputs/R09_fastSimCuts/qqqq_DataPreselected.root inputs/R09_fastSimCuts/qqvv_DataPreselected.root inputs/R09_fastSimCuts/qqlvlv_DataPreselected.root inputs/R09_fastSimCuts/qqlvvv_DataPreselected.root inputs/R09_fastSimCuts/qqqqlv_DataPreselected.root inputs/R09_fastSimCuts/qq_DataPreselected.root",
         			   "BP23",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   14150.0,
         			   1663980.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R09_fastSimCuts/HP17_DataPreselected.root",
         			   "inputs/R09_fastSimCuts/qqll_DataPreselected.root inputs/R09_fastSimCuts/qqlv_DataPreselected.root inputs/R09_fastSimCuts/ll_DataPreselected.root inputs/R09_fastSimCuts/qqqq_DataPreselected.root inputs/R09_fastSimCuts/qqvv_DataPreselected.root inputs/R09_fastSimCuts/qqlvlv_DataPreselected.root inputs/R09_fastSimCuts/qqlvvv_DataPreselected.root inputs/R09_fastSimCuts/qqqqlv_DataPreselected.root inputs/R09_fastSimCuts/qq_DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1605.0,
         			   1663980.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R09_fastSimCuts/HP20_DataPreselected.root",
         			   "inputs/R09_fastSimCuts/qqll_DataPreselected.root inputs/R09_fastSimCuts/qqlv_DataPreselected.root inputs/R09_fastSimCuts/ll_DataPreselected.root inputs/R09_fastSimCuts/qqqq_DataPreselected.root inputs/R09_fastSimCuts/qqvv_DataPreselected.root inputs/R09_fastSimCuts/qqlvlv_DataPreselected.root inputs/R09_fastSimCuts/qqlvvv_DataPreselected.root inputs/R09_fastSimCuts/qqqqlv_DataPreselected.root inputs/R09_fastSimCuts/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1500.0,
         			   1663980.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt

root -l -q my_mva_selection_ss.C++'("inputs/R09_fastSimCuts/HP3_DataPreselected.root",
         			   "inputs/R09_fastSimCuts/qqll_DataPreselected.root inputs/R09_fastSimCuts/qqlv_DataPreselected.root inputs/R09_fastSimCuts/ll_DataPreselected.root inputs/R09_fastSimCuts/qqqq_DataPreselected.root inputs/R09_fastSimCuts/qqvv_DataPreselected.root inputs/R09_fastSimCuts/qqlvlv_DataPreselected.root inputs/R09_fastSimCuts/qqlvvv_DataPreselected.root inputs/R09_fastSimCuts/qqqqlv_DataPreselected.root inputs/R09_fastSimCuts/qq_DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   749.0,
         			   1663980.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> singleSampleResults.txt
