#!/bin/bash

echo 'channel (  #signal, #backgr.)  Optimal-cut  S/sqrt(S+B)      NSig      NBkg   EffSig   EffBkg (PCA, no pruning, full sim cuts Mjj > 3, pT_lep > 2, qq bg. included, same var. ordering as in samples)' >> outSig.txt

root -l -q my_mva_selection_test.C++'("inputs/R09_allBackgrounds_withCuts/BP21_DataPreselected.root inputs/R09_allBackgrounds_withCuts/BP23_DataPreselected.root",
         			   "inputs/R09_allBackgrounds_withCuts/qqll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/ll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqq_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qq_DataPreselected.root",
         			   "BP21",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   9100.0,
         			   1617271.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP21",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection_test.C++'("inputs/R09_allBackgrounds_withCuts/BP21_DataPreselected.root inputs/R09_allBackgrounds_withCuts/BP23_DataPreselected.root",
         			   "inputs/R09_allBackgrounds_withCuts/qqll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/ll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqq_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qq_DataPreselected.root",
         			   "BP23",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   14136.0,
         			   1617271.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "BP23",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection_test.C++'("inputs/R09_allBackgrounds_withCuts/HP17_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP20_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP3_DataPreselected.root",
         			   "inputs/R09_allBackgrounds_withCuts/qqll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/ll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqq_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qq_DataPreselected.root",
         			   "HP17",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1588.0,
         			   1617271.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP17",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection_test.C++'("inputs/R09_allBackgrounds_withCuts/HP17_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP20_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP3_DataPreselected.root",
         			   "inputs/R09_allBackgrounds_withCuts/qqll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/ll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqq_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qq_DataPreselected.root",
         			   "HP20",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   1495.0,
         			   1617271.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP20",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt

root -l -q my_mva_selection_test.C++'("inputs/R09_allBackgrounds_withCuts/HP17_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP20_DataPreselected.root inputs/R09_allBackgrounds_withCuts/HP3_DataPreselected.root",
         			   "inputs/R09_allBackgrounds_withCuts/qqll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/ll_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqq_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqlvvv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qqqqlv_DataPreselected.root inputs/R09_allBackgrounds_withCuts/qq_DataPreselected.root",
         			   "HP3",
         			   "",
         				 "jetsM_inv M_inv_Wlep jetsEnergy jetsTheta jet1Theta jet2Theta jet1Pt jet2Pt jet1E jet2E leptonEnergy leptonTheta leptonPt jetDeltaTheta jetDeltaPhi EFsum MET missingMass",
         			   "w",
         			   748.0,
         			   1617271.0,
         			   "",
         			   "",
         			   "w",
         			   "my_mva_selection",
         			   "1000",
         			   "P",
         			   "UseNvars=6")' | awk '/^---        BDT:/ {print "HP3",$3,$4,$5,$6,$7,$8,$9,$10,$11}' >> outSig.txt
